"""Integration tests for complete trading flows."""
import pytest
from datetime import datetime, timedelta
from app.models.trading import PaperTrade


class TestSignalToTradeFlow:
    """Test end-to-end flow from signal generation to trade exit."""

    def test_signal_generation_to_paper_trade_creation(self, db_session, mock_signal):
        """Test full flow: signal generated -> paper trade created."""
        # Signal would be generated by option_signal_generator
        signal_data = {
            "quality_score": mock_signal["quality"],
            "confirmation_score": mock_signal["confirmation"],
            "ai_edge_score": mock_signal["ai_edge"],
            "signal_type": mock_signal.get("signal_type", "index"),
        }

        # Create paper trade from signal
        trade = PaperTrade(
            symbol=mock_signal["symbol"],
            side=mock_signal["side"],
            entry_price=mock_signal["entry_price"],
            stop_loss=mock_signal["stop_loss"],
            target=mock_signal["target"],
            quantity=mock_signal["quantity"],
            signal_data=signal_data,
            entry_time=datetime.utcnow(),
            status="OPEN",
        )
        db_session.add(trade)
        db_session.commit()

        # Verify trade created
        retrieved = db_session.query(PaperTrade).filter_by(
            symbol=mock_signal["symbol"]
        ).first()
        assert retrieved is not None
        assert retrieved.status == "OPEN"
        assert retrieved.signal_data["quality_score"] == mock_signal["quality"]

    def test_trade_price_update_to_target_hit(self, db_session, sample_paper_trade):
        """Test trade updating price until target is hit."""
        # Initial entry
        assert sample_paper_trade.status == "OPEN"
        assert sample_paper_trade.pnl == 0.0

        # Simulate price reaching target
        sample_paper_trade.exit_price = sample_paper_trade.target
        sample_paper_trade.exit_time = datetime.utcnow()
        sample_paper_trade.status = "TARGET_HIT"
        db_session.commit()

        # Verify PnL calculated
        expected_pnl = (
            sample_paper_trade.target - sample_paper_trade.entry_price
        ) * sample_paper_trade.quantity
        assert sample_paper_trade.pnl == pytest.approx(expected_pnl, rel=1e-2)

    def test_trade_price_update_to_sl_hit(self, db_session, sample_paper_trade):
        """Test trade updating price until SL is hit."""
        # Initial entry
        assert sample_paper_trade.status == "OPEN"

        # Simulate price reaching SL
        sample_paper_trade.exit_price = sample_paper_trade.stop_loss
        sample_paper_trade.exit_time = datetime.utcnow()
        sample_paper_trade.status = "SL_HIT"
        db_session.commit()

        # Verify loss calculated
        expected_pnl = (
            sample_paper_trade.stop_loss - sample_paper_trade.entry_price
        ) * sample_paper_trade.quantity
        assert sample_paper_trade.pnl == pytest.approx(expected_pnl, rel=1e-2)

    def test_trade_profit_lock_classification(self, db_session):
        """Test trade classified as PROFIT_TRAIL when exiting above entry."""
        # Entry at 287.50, SL at 275.00, target 314.85
        # Exit at 300 (between entry and target, but above entry + profit lock threshold)
        trade = PaperTrade(
            symbol="NIFTY2631723850PE",
            side="BUY",
            entry_price=287.50,
            stop_loss=275.00,
            target=314.85,
            quantity=65,
            exit_price=300.00,
            exit_time=datetime.utcnow(),
            status="PROFIT_TRAIL",
        )
        db_session.add(trade)
        db_session.commit()

        # Verify profit calculated (positive)
        expected_pnl = (300.00 - 287.50) * 65
        assert trade.pnl > 0
        assert trade.pnl == pytest.approx(expected_pnl, rel=1e-2)

    def test_quality_gate_rejection_prevents_trade(self, db_session):
        """Test low-quality signal is rejected before trade creation."""
        low_quality_signal = {
            "quality_score": 40.0,  # Below any threshold
            "confirmation_score": 50.0,
            "ai_edge_score": 10.0,
            "signal_type": "index",
        }

        # Trade should not be created for low-quality signal
        quality_min = 55  # For index signals
        should_create = low_quality_signal["quality_score"] >= quality_min

        assert should_create is False

    def test_same_move_reentry_prevented(self, db_session):
        """Test that re-entry on same move improvement is prevented."""
        now = datetime.utcnow()

        # First trade at 287.50, exits at 285 (small loss)
        first_trade = PaperTrade(
            symbol="NIFTY2631723850PE",
            side="BUY",
            entry_price=287.50,
            stop_loss=275.00,
            target=314.85,
            quantity=65,
            entry_time=now,
            exit_price=285.00,
            exit_time=now + timedelta(seconds=30),
            status="MANUAL_CLOSE",
        )
        db_session.add(first_trade)

        # Re-entry attempt at 286 (0.5 point improvement) - should be blocked
        # Re-entry at 293+ (6+ point improvement) - should be allowed
        reentry_price_1 = 286.00  # 1.5 point improvement -> blocked
        reentry_price_2 = 294.00  # 6.5 point improvement -> allowed

        improvement_1 = reentry_price_1 - first_trade.exit_price
        improvement_2 = reentry_price_2 - first_trade.exit_price

        # Guard requires minimum 5-point improvement
        min_improvement = 5.0
        should_allow_1 = improvement_1 >= min_improvement
        should_allow_2 = improvement_2 >= min_improvement

        assert should_allow_1 is False
        assert should_allow_2 is True


class TestDailyLimitEnforcement:
    """Test daily limit enforcement across trade lifecycle."""

    def test_daily_trade_count_accumulated(self, db_session):
        """Test that daily trade count accumulates."""
        now = datetime.utcnow()
        
        # Create 5 trades today
        for i in range(5):
            trade = PaperTrade(
                symbol=f"NIFTY{i}",
                side="BUY",
                entry_price=100.0,
                stop_loss=90.0,
                target=110.0,
                quantity=50,
                entry_time=now - timedelta(minutes=i),
            )
            db_session.add(trade)
        db_session.commit()

        # Count daily trades
        trades_today = (
            db_session.query(PaperTrade)
            .filter(PaperTrade.entry_time >= now.replace(hour=0, minute=0, second=0))
            .count()
        )
        assert trades_today == 5

    def test_old_trades_not_counted(self, db_session):
        """Test that yesterday's trades are not counted in daily limit."""
        now = datetime.utcnow()
        yesterday = now - timedelta(days=1)

        # Add trade from yesterday
        old_trade = PaperTrade(
            symbol="NIFTY_OLD",
            side="BUY",
            entry_price=100.0,
            stop_loss=90.0,
            target=110.0,
            quantity=50,
            entry_time=yesterday,
        )
        db_session.add(old_trade)

        # Add trade from today
        new_trade = PaperTrade(
            symbol="NIFTY_NEW",
            side="BUY",
            entry_price=100.0,
            stop_loss=90.0,
            target=110.0,
            quantity=50,
            entry_time=now,
        )
        db_session.add(new_trade)
        db_session.commit()

        # Count today's trades
        today_start = now.replace(hour=0, minute=0, second=0)
        trades_today = (
            db_session.query(PaperTrade)
            .filter(PaperTrade.entry_time >= today_start)
            .count()
        )
        assert trades_today == 1

    def test_profit_target_accumulation(self, db_session):
        """Test that daily PnL accumulates toward profit target."""
        now = datetime.utcnow()
        
        # Create 3 profitable trades
        for i in range(3):
            trade = PaperTrade(
                symbol=f"NIFTY{i}",
                side="BUY",
                entry_price=1000.0,
                stop_loss=990.0,
                target=1100.0,
                quantity=50,
                exit_price=1100.0,
                exit_time=now + timedelta(minutes=i),
                status="TARGET_HIT",
            )
            db_session.add(trade)
        db_session.commit()

        # Calculate total daily PnL
        total_pnl = (1100.0 - 1000.0) * 50 * 3
        profit_target = 5000.0
        
        assert total_pnl == 15000.0
        assert total_pnl >= profit_target


class TestConsecutiveSLTracking:
    """Test consecutive SL_HIT tracking."""

    def test_consecutive_sl_count_resets_on_win(self, db_session):
        """Test that consecutive SL count resets on winning trade."""
        now = datetime.utcnow()

        # SL_HIT, SL_HIT, WIN sequence
        trades_sequence = [
            ("SL", 90.0, 0),
            ("SL", 90.0, 1),
            ("WIN", 110.0, 2),
        ]

        for idx, (status_type, exit_price, minute_offset) in enumerate(trades_sequence):
            trade = PaperTrade(
                symbol=f"NIFTY{idx}",
                side="BUY",
                entry_price=100.0,
                stop_loss=90.0,
                target=110.0,
                quantity=50,
                exit_price=exit_price,
                exit_time=now + timedelta(minutes=minute_offset),
                status="SL_HIT" if status_type == "SL" else "TARGET_HIT",
            )
            db_session.add(trade)
        db_session.commit()

        # Count consecutive SL_HIT from most recent backward
        trades_ordered = (
            db_session.query(PaperTrade)
            .order_by(PaperTrade.exit_time.desc())
            .all()
        )

        consecutive_sl = 0
        for trade in trades_ordered:
            if trade.status == "SL_HIT":
                consecutive_sl += 1
            else:
                break

        # Should reset to 0 because most recent is WIN
        assert consecutive_sl == 0

    def test_three_consecutive_sl_blocks_trading(self, db_session):
        """Test that 3 consecutive SL_HIT blocks new trades."""
        now = datetime.utcnow()

        # Create 3 consecutive SL_HIT trades
        for i in range(3):
            trade = PaperTrade(
                symbol=f"NIFTY{i}",
                side="BUY",
                entry_price=100.0,
                stop_loss=90.0,
                target=110.0,
                quantity=50,
                exit_price=90.0,
                exit_time=now - timedelta(minutes=(3 - i)),
                status="SL_HIT",
            )
            db_session.add(trade)
        db_session.commit()

        # Check if should allow new trade
        trades_ordered = (
            db_session.query(PaperTrade)
            .order_by(PaperTrade.exit_time.desc())
            .limit(3)
            .all()
        )

        consecutive_sl = sum(1 for t in trades_ordered if t.status == "SL_HIT")
        should_allow = consecutive_sl < 3

        assert should_allow is False


class TestBackfillOnRead:
    """Test backfill logic on reading history."""

    def test_backfill_corrects_mislabeled_exits(self, db_session):
        """Test that backfill corrects mislabeled PROFIT_TRAIL as SL_HIT."""
        # Create trade that was mislabeled
        # Entry at 130, SL at 96, exits at 115 - should be PROFIT_TRAIL not SL_HIT
        trade = PaperTrade(
            symbol="TEST",
            side="BUY",
            entry_price=130.0,
            stop_loss=96.0,
            target=150.0,
            quantity=100,
            exit_price=115.0,
            exit_time=datetime.utcnow() - timedelta(days=1),
            status="SL_HIT",  # Incorrectly labeled
        )
        db_session.add(trade)
        db_session.commit()

        # On read, backfill should correct this
        # Since exit_price (115) > entry_price (130)? No, 115 < 130
        # But 115 > stop_loss (96), so this is PROFIT_TRAIL

        if trade.exit_price and trade.exit_price > trade.stop_loss:
            if not (trade.side == "BUY" and trade.exit_price >= trade.entry_price):
                # This is profit-lock territory
                correct_status = "PROFIT_TRAIL" if trade.exit_price > trade.entry_price else "SL_HIT"
                
                if correct_status != trade.status:
                    trade.status = correct_status
                    db_session.commit()

        # Verify correction applied
        retrieved = db_session.query(PaperTrade).first()
        # Note: In this case, 115 < 130, so it remains SL_HIT (correct)
        # Backfill only corrects when: exit > entry (profit lock)

    def test_multiple_backfill_targets(self, db_session):
        """Test backfill handles multiple incorrectly labeled trades."""
        base_time = datetime.utcnow() - timedelta(days=1)

        # Create multiple mislabeled trades
        for i in range(5):
            trade = PaperTrade(
                symbol=f"TEST{i}",
                side="BUY",
                entry_price=100.0,
                stop_loss=90.0,
                target=110.0,
                quantity=50,
                exit_price=105.0,  # Above entry, should be PROFIT_TRAIL
                exit_time=base_time + timedelta(minutes=i),
                status="SL_HIT",  # Incorrectly labeled
            )
            db_session.add(trade)
        db_session.commit()

        # Simulate backfill on read
        mislabeled_trades = db_session.query(PaperTrade).filter_by(status="SL_HIT").all()
        
        for trade in mislabeled_trades:
            if trade.exit_price and trade.exit_price >= trade.entry_price:
                trade.status = "PROFIT_TRAIL"

        db_session.commit()

        # Verify all corrected
        corrected = db_session.query(PaperTrade).filter_by(status="PROFIT_TRAIL").count()
        assert corrected == 5


class TestStockVsIndexFlow:
    """Test different handling for stock vs index signals."""

    def test_index_signal_strict_gates(self, db_session, mock_signal):
        """Test index signal passes strict quality gates."""
        # Index signal: quality 95 >= 55, confirmation 94.4 >= 60, ai_edge 25 >= 20
        quality_min = 55
        confirmation_min = 60
        ai_edge_min = 20.0

        should_accept = (
            mock_signal["quality"] >= quality_min
            and mock_signal["confirmation"] >= confirmation_min
            and mock_signal["ai_edge"] >= ai_edge_min
        )

        assert should_accept is True

    def test_stock_signal_relaxed_gates(self, db_session, mock_stock_signal):
        """Test stock signal passes relaxed quality gates."""
        # Stock signal: quality 70 >= 50, confirmation 65 >= 55, ai_edge 18 >= 15
        quality_min = 50
        confirmation_min = 55
        ai_edge_min = 15.0

        should_accept = (
            mock_stock_signal["quality"] >= quality_min
            and mock_stock_signal["confirmation"] >= confirmation_min
            and mock_stock_signal["ai_edge"] >= ai_edge_min
        )

        assert should_accept is True

    def test_stock_signal_rejected_by_index_gates(self, db_session, mock_stock_signal):
        """Test stock signal fails if index gates applied."""
        quality_min = 55  # Index threshold
        confirmation_min = 60

        should_accept = (
            mock_stock_signal["quality"] >= quality_min
            and mock_stock_signal["confirmation"] >= confirmation_min
        )

        # Stock signal (70% quality, 65% confirmation) would fail index gates
        assert should_accept is False
